apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      restartPolicy: Always
      containers:
        - name: backend
          image: alishahim/proshop-backend:latest
          imagePullPolicy: Always
          workingDir: /app
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: "development"
            - name: JWT_SECRET  # Здесь добавим просто переменную для секретного ключа
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  type: ClusterIP  # Или LoadBalancer, если нужно
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
