apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: final-frontend
  template:
    metadata:
      labels:
        app: final-frontend
    spec:
      containers:
      - name: frontend
        image: alishahim/proshop-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: final-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Change to ClusterIP if not exposing externally