name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/cache@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set in GitHub Secrets

      - name: Build Docker image
        run: |
          docker build -t my-frontend .
          docker build -t my-backend .

      - name: Push Docker images
        run: |
          docker push my-frontend
          docker push my-backend

      - name: Deploy to AWS
        run: |
          # Add your AWS deployment commands here, for example:
          # - aws ecs update-service --cluster my-cluster --service my-service
